### ISSUE TITLE
KeyError: '\\d'

### ISSUE THREAD

**Issue by abrac** [mapbox/untiler#29]
Hi, I recently installed untiler. When I run any of the untiler commands, I get the error attached below. I am using Python 3.9.1.

I'm   not sure if it's an issue with the python version, I am currently trying to downgrade my python version, and will update this issue accordingly.

```sh
in __exit__
Traceback (most recent call last):
  File "/usr/lib/python3.9/sre_parse.py", line 1039, in parse_template
    this = chr(ESCAPES[this][1])
KeyError: '\\d'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/c_abraham/.local/bin/untiler", line 8, in <module>
    sys.exit(cli())
  File "/usr/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/c_abraham/.local/lib/python3.9/site-packages/untiler/scripts/cli.py", line 53, in streammbtiles
    untiler.stream_dir(input_tile_dir, output_dir, compositezoom, maxzoom, None, readtemplate, scenetemplate, workers, creation_options, no_fill)
  File "/home/c_abraham/.local/lib/python3.9/site-packages/untiler/__init__.py", line 225, in stream_dir
    template, readTemplate, separator = tile_utils.parse_template("%s/%s" % (inputDir, read_template))
  File "/home/c_abraham/.local/lib/python3.9/site-packages/untiler/scripts/tile_utils.py", line 151, in parse_template
    return valPattern.sub('\d+', template), valPattern.sub('%s', template), separator[0]
  File "/usr/lib/python3.9/re.py", line 327, in _subx
    template = _compile_repl(template, pattern)
  File "/usr/lib/python3.9/re.py", line 318, in _compile_repl
    return sre_parse.parse_template(repl, pattern)
  File "/usr/lib/python3.9/sre_parse.py", line 1042, in parse_template
    raise s.error('bad escape %s' % this, len(this))
re.error: bad escape \d at position 0
```

**Comment by abrac** [comment]
I can confirm that this issue also persists in python 3.8.6. Not sure if you want me to downgrade to an earlier version? Hope you can advise me how to troubleshoot this error.

**Comment by bhavika** [comment]
@abrac 👋🏽 what version of `untiler` are you running? I think we might need to cut a new release.

**Comment by sgillies** [comment]
This project has some outdated re usage. Like a `"\d"` that needs to be `r"\d"`. @abrac this project hasn't had a release in over 3 years. I don't think we're going to have another one for this, so I suggest you patch the project for your needs.

**Comment by abrac** [comment]
Thanks for your support guys!!

@bhavika I first tried [v0.2.1 on Pip](https://pypi.org/project/untiler/). When that didn't work, I installed it from the latest commit from the git repo. That also didn't work.

@sgillies I made the change that you suggested, and suprisingly I got the exact same error! [See traceback](http://ix.io/2KPG/bash).

**Comment by abrac** [comment]
Eureka! I tried a couple of older python versions, and I got `untiler` to work with Python 3.6.12.  

Note to future visitors: You can run multiple versions of python on your system using [asdf](http://asdf-vm.com/).
